name: "Main"

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22.x
      - name: Install just
        uses: taiki-e/install-action@just
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Install
        run: npm ci
      - name: Test
        run: just test
  publish:
    if: startsWith(github.event.ref, 'refs/tags/v')
    needs: test
    runs-on: ubuntu-latest
    environment: npm
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22.x
          registry-url: https://registry.npmjs.org
      - name: Setup just
        uses: taiki-e/install-action@just
      - name: Install
        run: npm ci
      - name: Build
        run: just build
      - name: Update npm
        run: npm install -g npm@latest
      - name: Publish
        run: npm publish --provenance --access public
